variables:
  HEROKU_URL: "patientoncall.herokuapp.com/"

stages:
  - compile
  - test
  - deploy

compile-job:
  image: python:3.10
  stage: compile
  script:
    - python manage.py migrate

test-job:
  image: python:3.10
  stage: test
  script:
    - python manage.py test

deploy-heroku-job:
  stage: deploy
  script:
    - echo "Deploying to Heroku via Docker container:"
    - git push heroku master
  environment:
    name: deployment
    url: HEROKU_URL