variables:
  HEROKU_URL: "patientoncall.herokuapp.com/"

stages:
  - test
  - deploy

test-job:
  image: python:3.10
  stage: test
  script:
    - echo "Install requirements"
    - pip3 install -r requirements.txt
    - python manage.py migrate
    - python manage.py test

deploy-heroku-job:
  image: ruby:3.1.2
  stage: deploy
  script:
    - echo "Deploying to Heroku:"
    - gem install dpl
    - dpl --provider=heroku --app=patientoncall --api-key=$HEROKU_AUTH_TOKEN
  only:
    refs:
      - tags
      - master

  environment:
    name: deployment
    url: HEROKU_URL

deploy-flutter-job:
  image: "cirrusci/flutter:latest"
  stage: deploy
  script:
    - cd patient_mobile/
    - echo "Producing APK file for mobile app"
    - flutter build apk --split-per-abi --no-tree-shake-icons
  artifacts:
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths: 
      - build/app/outputs/flutter-apk/*.apk