variables:
  HEROKU_URL: "patientoncall.herokuapp.com/"

stages:
  - test
  - deploy

test-job:
  image: python:3.10
  stage: test
  script:
    - echo "Install requirements"
    - pip3 install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test

deploy-heroku-job:
  image: ruby:3.1.2
  stage: deploy
  script:
    - echo "Deploying to Heroku:"
    - gem install dpl
    - dpl --provider=heroku --app=patientoncall --api-key=$HEROKU_AUTH_TOKEN
  only:
    refs:
      - tags
      - master
  environment:
    name: deployment
    url: HEROKU_URL

migrate-heroku:
  stage: deploy
  image: registry.heroku.com/patientoncall/web
  script:
    - apt-get update && apt-get install -y heroku
    - heroku run python manage.py migrate --app patientoncall
  only:
    refs:
      - tags
      - master