variables:
  HEROKU_URL: "patientoncall.herokuapp.com/"

stages:
  - test
  - deploy

test-job:
  image: python:3.10
  stage: test
  script:
    - echo "Install requirements"
    - pip3 install -r requirements.txt
    - python manage.py migrate
    - python manage.py test

deploy-heroku-job:
  stage: deploy
  script:
    - echo "Deploying to Heroku via Docker container:"
    - git push heroku master
  environment:
    name: deployment
    url: HEROKU_URL