# Generated by Django 4.2.1 on 2023-06-05 23:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0009_medicalhistory_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labhistory',
            name='report',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='letter',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
