# Generated by Django 4.2.1 on 2023-06-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0013_delete_photo_alter_labhistory_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labhistory',
            name='report',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='letter',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
