# Generated by Django 4.2.1 on 2023-06-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0024_diary'),
        ('patientoncall_api', '0028_alter_imagingupload_id'),
    ]

    operations = [
    ]
