# Generated by Django 4.2.1 on 2023-06-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0030_medicalhistory_addbypatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='addByPatient',
        ),
    ]
