# Generated by Django 4.2.1 on 2023-06-14 02:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0030_merge_20230613_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagingupload',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
